theme:
  name: jackie
  version: 1.0
  author:
  link:
pages:
  BackgroundImage: String|背景图|http://10.86.8.21:8888/templates/jacikes/assets/images/bg.png
  TitleBackgroundImage: String|标题背景|http://10.86.8.21:8888/templates/jacikes/assets/images/title.png
  LunPanBackgroundImage: String|轮盘背景|http://10.86.8.21:8888/templates/jacikes/assets/images/circle.png
  LunPanBackgroundImageTop: String|轮盘距顶部高度|30%
  StartBtnBackgroundImage: String|开始按钮|http://10.86.8.21:8888/templates/jacikes/assets/images/button.png



